// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: proto/image_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PositivePrompt string                 `protobuf:"bytes,1,opt,name=positive_prompt,json=positivePrompt,proto3" json:"positive_prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,2,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_proto_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetPositivePrompt() string {
	if x != nil {
		return x.PositivePrompt
	}
	return ""
}

func (x *GenerateImageRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilenameHint  string                 `protobuf:"bytes,3,opt,name=filename_hint,json=filenameHint,proto3" json:"filename_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_proto_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateImageResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateImageResponse) GetFilenameHint() string {
	if x != nil {
		return x.FilenameHint
	}
	return ""
}

type GenerateMediaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PositivePrompt     string                 `protobuf:"bytes,1,opt,name=positive_prompt,json=positivePrompt,proto3" json:"positive_prompt,omitempty"`
	NegativePrompt     string                 `protobuf:"bytes,2,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	Mode               string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	InputImage         []byte                 `protobuf:"bytes,4,opt,name=input_image,json=inputImage,proto3" json:"input_image,omitempty"`
	InputImageMimeType string                 `protobuf:"bytes,5,opt,name=input_image_mime_type,json=inputImageMimeType,proto3" json:"input_image_mime_type,omitempty"`
	InputImageFilename string                 `protobuf:"bytes,6,opt,name=input_image_filename,json=inputImageFilename,proto3" json:"input_image_filename,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateMediaRequest) Reset() {
	*x = GenerateMediaRequest{}
	mi := &file_proto_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMediaRequest) ProtoMessage() {}

func (x *GenerateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMediaRequest.ProtoReflect.Descriptor instead.
func (*GenerateMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateMediaRequest) GetPositivePrompt() string {
	if x != nil {
		return x.PositivePrompt
	}
	return ""
}

func (x *GenerateMediaRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

func (x *GenerateMediaRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GenerateMediaRequest) GetInputImage() []byte {
	if x != nil {
		return x.InputImage
	}
	return nil
}

func (x *GenerateMediaRequest) GetInputImageMimeType() string {
	if x != nil {
		return x.InputImageMimeType
	}
	return ""
}

func (x *GenerateMediaRequest) GetInputImageFilename() string {
	if x != nil {
		return x.InputImageFilename
	}
	return ""
}

type GenerateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []byte                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilenameHint  string                 `protobuf:"bytes,3,opt,name=filename_hint,json=filenameHint,proto3" json:"filename_hint,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMediaResponse) Reset() {
	*x = GenerateMediaResponse{}
	mi := &file_proto_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMediaResponse) ProtoMessage() {}

func (x *GenerateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMediaResponse.ProtoReflect.Descriptor instead.
func (*GenerateMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateMediaResponse) GetMedia() []byte {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GenerateMediaResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateMediaResponse) GetFilenameHint() string {
	if x != nil {
		return x.FilenameHint
	}
	return ""
}

func (x *GenerateMediaResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

// List Modeles
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_image_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{4}
}

type ListModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPaths    []string               `protobuf:"bytes,1,rep,name=model_paths,json=modelPaths,proto3" json:"model_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelResponse) Reset() {
	*x = ListModelResponse{}
	mi := &file_proto_image_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelResponse) ProtoMessage() {}

func (x *ListModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelResponse.ProtoReflect.Descriptor instead.
func (*ListModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelResponse) GetModelPaths() []string {
	if x != nil {
		return x.ModelPaths
	}
	return nil
}

// Set Models
type SetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelRequest) Reset() {
	*x = SetModelRequest{}
	mi := &file_proto_image_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelRequest) ProtoMessage() {}

func (x *SetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelRequest.ProtoReflect.Descriptor instead.
func (*SetModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type SetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelResponse) Reset() {
	*x = SetModelResponse{}
	mi := &file_proto_image_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelResponse) ProtoMessage() {}

func (x *SetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelResponse.ProtoReflect.Descriptor instead.
func (*SetModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type GetCurrentModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentModelRequest) Reset() {
	*x = GetCurrentModelRequest{}
	mi := &file_proto_image_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentModelRequest) ProtoMessage() {}

func (x *GetCurrentModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentModelRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{8}
}

type GetCurrentModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentModelResponse) Reset() {
	*x = GetCurrentModelResponse{}
	mi := &file_proto_image_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentModelResponse) ProtoMessage() {}

func (x *GetCurrentModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentModelResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetCurrentModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type ClearModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearModelRequest) Reset() {
	*x = ClearModelRequest{}
	mi := &file_proto_image_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearModelRequest) ProtoMessage() {}

func (x *ClearModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearModelRequest.ProtoReflect.Descriptor instead.
func (*ClearModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{10}
}

type ClearModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	Loras         []*SetLora             `protobuf:"bytes,2,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearModelResponse) Reset() {
	*x = ClearModelResponse{}
	mi := &file_proto_image_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearModelResponse) ProtoMessage() {}

func (x *ClearModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearModelResponse.ProtoReflect.Descriptor instead.
func (*ClearModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{11}
}

func (x *ClearModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *ClearModelResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

// Set LLM Model
type SetLlmModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLlmModelRequest) Reset() {
	*x = SetLlmModelRequest{}
	mi := &file_proto_image_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLlmModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLlmModelRequest) ProtoMessage() {}

func (x *SetLlmModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLlmModelRequest.ProtoReflect.Descriptor instead.
func (*SetLlmModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{12}
}

func (x *SetLlmModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type SetLlmModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLlmModelResponse) Reset() {
	*x = SetLlmModelResponse{}
	mi := &file_proto_image_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLlmModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLlmModelResponse) ProtoMessage() {}

func (x *SetLlmModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLlmModelResponse.ProtoReflect.Descriptor instead.
func (*SetLlmModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{13}
}

func (x *SetLlmModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type GetCurrentLorasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLorasRequest) Reset() {
	*x = GetCurrentLorasRequest{}
	mi := &file_proto_image_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLorasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLorasRequest) ProtoMessage() {}

func (x *GetCurrentLorasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLorasRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentLorasRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{14}
}

type GetCurrentLorasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLorasResponse) Reset() {
	*x = GetCurrentLorasResponse{}
	mi := &file_proto_image_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLorasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLorasResponse) ProtoMessage() {}

func (x *GetCurrentLorasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLorasResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentLorasResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetCurrentLorasResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

type ClearLorasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLorasRequest) Reset() {
	*x = ClearLorasRequest{}
	mi := &file_proto_image_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLorasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLorasRequest) ProtoMessage() {}

func (x *ClearLorasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLorasRequest.ProtoReflect.Descriptor instead.
func (*ClearLorasRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{16}
}

type ClearLorasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLorasResponse) Reset() {
	*x = ClearLorasResponse{}
	mi := &file_proto_image_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLorasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLorasResponse) ProtoMessage() {}

func (x *ClearLorasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLorasResponse.ProtoReflect.Descriptor instead.
func (*ClearLorasResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{17}
}

func (x *ClearLorasResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

// List Loras
type ListLorasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLorasRequest) Reset() {
	*x = ListLorasRequest{}
	mi := &file_proto_image_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLorasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLorasRequest) ProtoMessage() {}

func (x *ListLorasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLorasRequest.ProtoReflect.Descriptor instead.
func (*ListLorasRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{18}
}

type ListLorasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoraPath      []string               `protobuf:"bytes,1,rep,name=lora_path,json=loraPath,proto3" json:"lora_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLorasResponse) Reset() {
	*x = ListLorasResponse{}
	mi := &file_proto_image_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLorasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLorasResponse) ProtoMessage() {}

func (x *ListLorasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLorasResponse.ProtoReflect.Descriptor instead.
func (*ListLorasResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListLorasResponse) GetLoraPath() []string {
	if x != nil {
		return x.LoraPath
	}
	return nil
}

// Set Loras
type SetLora struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float32                `protobuf:"fixed32,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLora) Reset() {
	*x = SetLora{}
	mi := &file_proto_image_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLora) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLora) ProtoMessage() {}

func (x *SetLora) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLora.ProtoReflect.Descriptor instead.
func (*SetLora) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{20}
}

func (x *SetLora) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SetLora) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetLoraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoraRequest) Reset() {
	*x = SetLoraRequest{}
	mi := &file_proto_image_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoraRequest) ProtoMessage() {}

func (x *SetLoraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoraRequest.ProtoReflect.Descriptor instead.
func (*SetLoraRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{21}
}

func (x *SetLoraRequest) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

type SetLoraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoraResponse) Reset() {
	*x = SetLoraResponse{}
	mi := &file_proto_image_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoraResponse) ProtoMessage() {}

func (x *SetLoraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoraResponse.ProtoReflect.Descriptor instead.
func (*SetLoraResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{22}
}

func (x *SetLoraResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

// rpc Conversation (ConversationRequest) returns stream (ConversationResponse);
type ConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationRequest) Reset() {
	*x = ConversationRequest{}
	mi := &file_proto_image_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRequest) ProtoMessage() {}

func (x *ConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRequest.ProtoReflect.Descriptor instead.
func (*ConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{23}
}

func (x *ConversationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConversationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type ConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_proto_image_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{24}
}

func (x *ConversationResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConversationResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_image_service_proto protoreflect.FileDescriptor

const file_proto_image_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/image_service.proto\x12\tgenerator\"h\n" +
	"\x14GenerateImageRequest\x12'\n" +
	"\x0fpositive_prompt\x18\x01 \x01(\tR\x0epositivePrompt\x12'\n" +
	"\x0fnegative_prompt\x18\x02 \x01(\tR\x0enegativePrompt\"o\n" +
	"\x15GenerateImageResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12#\n" +
	"\rfilename_hint\x18\x03 \x01(\tR\ffilenameHint\"\x82\x02\n" +
	"\x14GenerateMediaRequest\x12'\n" +
	"\x0fpositive_prompt\x18\x01 \x01(\tR\x0epositivePrompt\x12'\n" +
	"\x0fnegative_prompt\x18\x02 \x01(\tR\x0enegativePrompt\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1f\n" +
	"\vinput_image\x18\x04 \x01(\fR\n" +
	"inputImage\x121\n" +
	"\x15input_image_mime_type\x18\x05 \x01(\tR\x12inputImageMimeType\x120\n" +
	"\x14input_image_filename\x18\x06 \x01(\tR\x12inputImageFilename\"\x8e\x01\n" +
	"\x15GenerateMediaResponse\x12\x14\n" +
	"\x05media\x18\x01 \x01(\fR\x05media\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12#\n" +
	"\rfilename_hint\x18\x03 \x01(\tR\ffilenameHint\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\"\x13\n" +
	"\x11ListModelsRequest\"4\n" +
	"\x11ListModelResponse\x12\x1f\n" +
	"\vmodel_paths\x18\x01 \x03(\tR\n" +
	"modelPaths\"0\n" +
	"\x0fSetModelRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"1\n" +
	"\x10SetModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"\x18\n" +
	"\x16GetCurrentModelRequest\"8\n" +
	"\x17GetCurrentModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"\x13\n" +
	"\x11ClearModelRequest\"]\n" +
	"\x12ClearModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\x12(\n" +
	"\x05loras\x18\x02 \x03(\v2\x12.generator.SetLoraR\x05loras\"3\n" +
	"\x12SetLlmModelRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"4\n" +
	"\x13SetLlmModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"\x18\n" +
	"\x16GetCurrentLorasRequest\"C\n" +
	"\x17GetCurrentLorasResponse\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\"\x13\n" +
	"\x11ClearLorasRequest\">\n" +
	"\x12ClearLorasResponse\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\"\x12\n" +
	"\x10ListLorasRequest\"0\n" +
	"\x11ListLorasResponse\x12\x1b\n" +
	"\tlora_path\x18\x01 \x03(\tR\bloraPath\"5\n" +
	"\aSetLora\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x02R\x06weight\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\":\n" +
	"\x0eSetLoraRequest\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\";\n" +
	"\x0fSetLoraResponse\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\"I\n" +
	"\x13ConversationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"L\n" +
	"\x14ConversationResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage2\xba\a\n" +
	"\fImageService\x12R\n" +
	"\rGenerateImage\x12\x1f.generator.GenerateImageRequest\x1a .generator.GenerateImageResponse\x12R\n" +
	"\rGenerateMedia\x12\x1f.generator.GenerateMediaRequest\x1a .generator.GenerateMediaResponse\x12H\n" +
	"\n" +
	"ListModels\x12\x1c.generator.ListModelsRequest\x1a\x1c.generator.ListModelResponse\x12C\n" +
	"\bSetModel\x12\x1a.generator.SetModelRequest\x1a\x1b.generator.SetModelResponse\x12X\n" +
	"\x0fGetCurrentModel\x12!.generator.GetCurrentModelRequest\x1a\".generator.GetCurrentModelResponse\x12I\n" +
	"\n" +
	"ClearModel\x12\x1c.generator.ClearModelRequest\x1a\x1d.generator.ClearModelResponse\x12L\n" +
	"\vSetLlmModel\x12\x1d.generator.SetLlmModelRequest\x1a\x1e.generator.SetLlmModelResponse\x12F\n" +
	"\tListLoras\x12\x1b.generator.ListLorasRequest\x1a\x1c.generator.ListLorasResponse\x12@\n" +
	"\aSetLora\x12\x19.generator.SetLoraRequest\x1a\x1a.generator.SetLoraResponse\x12X\n" +
	"\x0fGetCurrentLoras\x12!.generator.GetCurrentLorasRequest\x1a\".generator.GetCurrentLorasResponse\x12I\n" +
	"\n" +
	"ClearLoras\x12\x1c.generator.ClearLorasRequest\x1a\x1d.generator.ClearLorasResponse\x12Q\n" +
	"\fConversation\x12\x1e.generator.ConversationRequest\x1a\x1f.generator.ConversationResponse0\x01B\bZ\x06proto/b\x06proto3"

var (
	file_proto_image_service_proto_rawDescOnce sync.Once
	file_proto_image_service_proto_rawDescData []byte
)

func file_proto_image_service_proto_rawDescGZIP() []byte {
	file_proto_image_service_proto_rawDescOnce.Do(func() {
		file_proto_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_service_proto_rawDesc), len(file_proto_image_service_proto_rawDesc)))
	})
	return file_proto_image_service_proto_rawDescData
}

var file_proto_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_image_service_proto_goTypes = []any{
	(*GenerateImageRequest)(nil),    // 0: generator.GenerateImageRequest
	(*GenerateImageResponse)(nil),   // 1: generator.GenerateImageResponse
	(*GenerateMediaRequest)(nil),    // 2: generator.GenerateMediaRequest
	(*GenerateMediaResponse)(nil),   // 3: generator.GenerateMediaResponse
	(*ListModelsRequest)(nil),       // 4: generator.ListModelsRequest
	(*ListModelResponse)(nil),       // 5: generator.ListModelResponse
	(*SetModelRequest)(nil),         // 6: generator.SetModelRequest
	(*SetModelResponse)(nil),        // 7: generator.SetModelResponse
	(*GetCurrentModelRequest)(nil),  // 8: generator.GetCurrentModelRequest
	(*GetCurrentModelResponse)(nil), // 9: generator.GetCurrentModelResponse
	(*ClearModelRequest)(nil),       // 10: generator.ClearModelRequest
	(*ClearModelResponse)(nil),      // 11: generator.ClearModelResponse
	(*SetLlmModelRequest)(nil),      // 12: generator.SetLlmModelRequest
	(*SetLlmModelResponse)(nil),     // 13: generator.SetLlmModelResponse
	(*GetCurrentLorasRequest)(nil),  // 14: generator.GetCurrentLorasRequest
	(*GetCurrentLorasResponse)(nil), // 15: generator.GetCurrentLorasResponse
	(*ClearLorasRequest)(nil),       // 16: generator.ClearLorasRequest
	(*ClearLorasResponse)(nil),      // 17: generator.ClearLorasResponse
	(*ListLorasRequest)(nil),        // 18: generator.ListLorasRequest
	(*ListLorasResponse)(nil),       // 19: generator.ListLorasResponse
	(*SetLora)(nil),                 // 20: generator.SetLora
	(*SetLoraRequest)(nil),          // 21: generator.SetLoraRequest
	(*SetLoraResponse)(nil),         // 22: generator.SetLoraResponse
	(*ConversationRequest)(nil),     // 23: generator.ConversationRequest
	(*ConversationResponse)(nil),    // 24: generator.ConversationResponse
}
var file_proto_image_service_proto_depIdxs = []int32{
	20, // 0: generator.ClearModelResponse.loras:type_name -> generator.SetLora
	20, // 1: generator.GetCurrentLorasResponse.loras:type_name -> generator.SetLora
	20, // 2: generator.ClearLorasResponse.loras:type_name -> generator.SetLora
	20, // 3: generator.SetLoraRequest.loras:type_name -> generator.SetLora
	20, // 4: generator.SetLoraResponse.loras:type_name -> generator.SetLora
	0,  // 5: generator.ImageService.GenerateImage:input_type -> generator.GenerateImageRequest
	2,  // 6: generator.ImageService.GenerateMedia:input_type -> generator.GenerateMediaRequest
	4,  // 7: generator.ImageService.ListModels:input_type -> generator.ListModelsRequest
	6,  // 8: generator.ImageService.SetModel:input_type -> generator.SetModelRequest
	8,  // 9: generator.ImageService.GetCurrentModel:input_type -> generator.GetCurrentModelRequest
	10, // 10: generator.ImageService.ClearModel:input_type -> generator.ClearModelRequest
	12, // 11: generator.ImageService.SetLlmModel:input_type -> generator.SetLlmModelRequest
	18, // 12: generator.ImageService.ListLoras:input_type -> generator.ListLorasRequest
	21, // 13: generator.ImageService.SetLora:input_type -> generator.SetLoraRequest
	14, // 14: generator.ImageService.GetCurrentLoras:input_type -> generator.GetCurrentLorasRequest
	16, // 15: generator.ImageService.ClearLoras:input_type -> generator.ClearLorasRequest
	23, // 16: generator.ImageService.Conversation:input_type -> generator.ConversationRequest
	1,  // 17: generator.ImageService.GenerateImage:output_type -> generator.GenerateImageResponse
	3,  // 18: generator.ImageService.GenerateMedia:output_type -> generator.GenerateMediaResponse
	5,  // 19: generator.ImageService.ListModels:output_type -> generator.ListModelResponse
	7,  // 20: generator.ImageService.SetModel:output_type -> generator.SetModelResponse
	9,  // 21: generator.ImageService.GetCurrentModel:output_type -> generator.GetCurrentModelResponse
	11, // 22: generator.ImageService.ClearModel:output_type -> generator.ClearModelResponse
	13, // 23: generator.ImageService.SetLlmModel:output_type -> generator.SetLlmModelResponse
	19, // 24: generator.ImageService.ListLoras:output_type -> generator.ListLorasResponse
	22, // 25: generator.ImageService.SetLora:output_type -> generator.SetLoraResponse
	15, // 26: generator.ImageService.GetCurrentLoras:output_type -> generator.GetCurrentLorasResponse
	17, // 27: generator.ImageService.ClearLoras:output_type -> generator.ClearLorasResponse
	24, // 28: generator.ImageService.Conversation:output_type -> generator.ConversationResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_image_service_proto_init() }
func file_proto_image_service_proto_init() {
	if File_proto_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_service_proto_rawDesc), len(file_proto_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_service_proto_goTypes,
		DependencyIndexes: file_proto_image_service_proto_depIdxs,
		MessageInfos:      file_proto_image_service_proto_msgTypes,
	}.Build()
	File_proto_image_service_proto = out.File
	file_proto_image_service_proto_goTypes = nil
	file_proto_image_service_proto_depIdxs = nil
}
