// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: image_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelType int32

const (
	ModelType__UNKOWN ModelType = 0
	ModelType_t2i     ModelType = 1
	ModelType_i2v     ModelType = 2
)

// Enum value maps for ModelType.
var (
	ModelType_name = map[int32]string{
		0: "_UNKOWN",
		1: "t2i",
		2: "i2v",
	}
	ModelType_value = map[string]int32{
		"_UNKOWN": 0,
		"t2i":     1,
		"i2v":     2,
	}
)

func (x ModelType) Enum() *ModelType {
	p := new(ModelType)
	*p = x
	return p
}

func (x ModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_image_service_proto_enumTypes[0].Descriptor()
}

func (ModelType) Type() protoreflect.EnumType {
	return &file_image_service_proto_enumTypes[0]
}

func (x ModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelType.Descriptor instead.
func (ModelType) EnumDescriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{0}
}

type GenerateImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PositivePrompt string                 `protobuf:"bytes,1,opt,name=positive_prompt,json=positivePrompt,proto3" json:"positive_prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,2,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetPositivePrompt() string {
	if x != nil {
		return x.PositivePrompt
	}
	return ""
}

func (x *GenerateImageRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilenameHint  string                 `protobuf:"bytes,3,opt,name=filename_hint,json=filenameHint,proto3" json:"filename_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateImageResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateImageResponse) GetFilenameHint() string {
	if x != nil {
		return x.FilenameHint
	}
	return ""
}

// List Modeles
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{2}
}

type ListModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPaths    []string               `protobuf:"bytes,1,rep,name=model_paths,json=modelPaths,proto3" json:"model_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelResponse) Reset() {
	*x = ListModelResponse{}
	mi := &file_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelResponse) ProtoMessage() {}

func (x *ListModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelResponse.ProtoReflect.Descriptor instead.
func (*ListModelResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelResponse) GetModelPaths() []string {
	if x != nil {
		return x.ModelPaths
	}
	return nil
}

// Set Models
type SetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	ModelType     ModelType              `protobuf:"varint,2,opt,name=model_type,json=modelType,proto3,enum=generator.ModelType" json:"model_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelRequest) Reset() {
	*x = SetModelRequest{}
	mi := &file_image_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelRequest) ProtoMessage() {}

func (x *SetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelRequest.ProtoReflect.Descriptor instead.
func (*SetModelRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *SetModelRequest) GetModelType() ModelType {
	if x != nil {
		return x.ModelType
	}
	return ModelType__UNKOWN
}

type SetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelResponse) Reset() {
	*x = SetModelResponse{}
	mi := &file_image_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelResponse) ProtoMessage() {}

func (x *SetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelResponse.ProtoReflect.Descriptor instead.
func (*SetModelResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type GetCurrentModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentModelRequest) Reset() {
	*x = GetCurrentModelRequest{}
	mi := &file_image_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentModelRequest) ProtoMessage() {}

func (x *GetCurrentModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentModelRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentModelRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{6}
}

type GetCurrentModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentModelResponse) Reset() {
	*x = GetCurrentModelResponse{}
	mi := &file_image_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentModelResponse) ProtoMessage() {}

func (x *GetCurrentModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentModelResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentModelResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetCurrentModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type ClearModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearModelRequest) Reset() {
	*x = ClearModelRequest{}
	mi := &file_image_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearModelRequest) ProtoMessage() {}

func (x *ClearModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearModelRequest.ProtoReflect.Descriptor instead.
func (*ClearModelRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{8}
}

type ClearModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	Loras         []*SetLora             `protobuf:"bytes,2,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearModelResponse) Reset() {
	*x = ClearModelResponse{}
	mi := &file_image_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearModelResponse) ProtoMessage() {}

func (x *ClearModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearModelResponse.ProtoReflect.Descriptor instead.
func (*ClearModelResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{9}
}

func (x *ClearModelResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *ClearModelResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

type GetCurrentLorasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLorasRequest) Reset() {
	*x = GetCurrentLorasRequest{}
	mi := &file_image_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLorasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLorasRequest) ProtoMessage() {}

func (x *GetCurrentLorasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLorasRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentLorasRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{10}
}

type GetCurrentLorasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLorasResponse) Reset() {
	*x = GetCurrentLorasResponse{}
	mi := &file_image_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLorasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLorasResponse) ProtoMessage() {}

func (x *GetCurrentLorasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLorasResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentLorasResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCurrentLorasResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

type ClearLorasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLorasRequest) Reset() {
	*x = ClearLorasRequest{}
	mi := &file_image_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLorasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLorasRequest) ProtoMessage() {}

func (x *ClearLorasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLorasRequest.ProtoReflect.Descriptor instead.
func (*ClearLorasRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{12}
}

type ClearLorasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLorasResponse) Reset() {
	*x = ClearLorasResponse{}
	mi := &file_image_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLorasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLorasResponse) ProtoMessage() {}

func (x *ClearLorasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLorasResponse.ProtoReflect.Descriptor instead.
func (*ClearLorasResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{13}
}

func (x *ClearLorasResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

// List Loras
type ListLorasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLorasRequest) Reset() {
	*x = ListLorasRequest{}
	mi := &file_image_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLorasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLorasRequest) ProtoMessage() {}

func (x *ListLorasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLorasRequest.ProtoReflect.Descriptor instead.
func (*ListLorasRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{14}
}

type ListLorasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoraPath      []string               `protobuf:"bytes,1,rep,name=lora_path,json=loraPath,proto3" json:"lora_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLorasResponse) Reset() {
	*x = ListLorasResponse{}
	mi := &file_image_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLorasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLorasResponse) ProtoMessage() {}

func (x *ListLorasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLorasResponse.ProtoReflect.Descriptor instead.
func (*ListLorasResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListLorasResponse) GetLoraPath() []string {
	if x != nil {
		return x.LoraPath
	}
	return nil
}

// Set Loras
type SetLora struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float32                `protobuf:"fixed32,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLora) Reset() {
	*x = SetLora{}
	mi := &file_image_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLora) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLora) ProtoMessage() {}

func (x *SetLora) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLora.ProtoReflect.Descriptor instead.
func (*SetLora) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{16}
}

func (x *SetLora) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SetLora) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetLoraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoraRequest) Reset() {
	*x = SetLoraRequest{}
	mi := &file_image_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoraRequest) ProtoMessage() {}

func (x *SetLoraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoraRequest.ProtoReflect.Descriptor instead.
func (*SetLoraRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{17}
}

func (x *SetLoraRequest) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

type SetLoraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loras         []*SetLora             `protobuf:"bytes,1,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoraResponse) Reset() {
	*x = SetLoraResponse{}
	mi := &file_image_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoraResponse) ProtoMessage() {}

func (x *SetLoraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoraResponse.ProtoReflect.Descriptor instead.
func (*SetLoraResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{18}
}

func (x *SetLoraResponse) GetLoras() []*SetLora {
	if x != nil {
		return x.Loras
	}
	return nil
}

// Image to Video
type GenerateImageToVideoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Image          []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	PositivePrompt string                 `protobuf:"bytes,2,opt,name=positive_prompt,json=positivePrompt,proto3" json:"positive_prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,3,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImageToVideoRequest) Reset() {
	*x = GenerateImageToVideoRequest{}
	mi := &file_image_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageToVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageToVideoRequest) ProtoMessage() {}

func (x *GenerateImageToVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageToVideoRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageToVideoRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateImageToVideoRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateImageToVideoRequest) GetPositivePrompt() string {
	if x != nil {
		return x.PositivePrompt
	}
	return ""
}

func (x *GenerateImageToVideoRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

type GenerateImageToVideoResonse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         []byte                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilenameHint  string                 `protobuf:"bytes,3,opt,name=filename_hint,json=filenameHint,proto3" json:"filename_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageToVideoResonse) Reset() {
	*x = GenerateImageToVideoResonse{}
	mi := &file_image_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageToVideoResonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageToVideoResonse) ProtoMessage() {}

func (x *GenerateImageToVideoResonse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageToVideoResonse.ProtoReflect.Descriptor instead.
func (*GenerateImageToVideoResonse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateImageToVideoResonse) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *GenerateImageToVideoResonse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateImageToVideoResonse) GetFilenameHint() string {
	if x != nil {
		return x.FilenameHint
	}
	return ""
}

var File_image_service_proto protoreflect.FileDescriptor

const file_image_service_proto_rawDesc = "" +
	"\n" +
	"\x13image_service.proto\x12\tgenerator\"h\n" +
	"\x14GenerateImageRequest\x12'\n" +
	"\x0fpositive_prompt\x18\x01 \x01(\tR\x0epositivePrompt\x12'\n" +
	"\x0fnegative_prompt\x18\x02 \x01(\tR\x0enegativePrompt\"o\n" +
	"\x15GenerateImageResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12#\n" +
	"\rfilename_hint\x18\x03 \x01(\tR\ffilenameHint\"\x13\n" +
	"\x11ListModelsRequest\"4\n" +
	"\x11ListModelResponse\x12\x1f\n" +
	"\vmodel_paths\x18\x01 \x03(\tR\n" +
	"modelPaths\"e\n" +
	"\x0fSetModelRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\x123\n" +
	"\n" +
	"model_type\x18\x02 \x01(\x0e2\x14.generator.ModelTypeR\tmodelType\"1\n" +
	"\x10SetModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"\x18\n" +
	"\x16GetCurrentModelRequest\"8\n" +
	"\x17GetCurrentModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"\x13\n" +
	"\x11ClearModelRequest\"]\n" +
	"\x12ClearModelResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\x12(\n" +
	"\x05loras\x18\x02 \x03(\v2\x12.generator.SetLoraR\x05loras\"\x18\n" +
	"\x16GetCurrentLorasRequest\"C\n" +
	"\x17GetCurrentLorasResponse\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\"\x13\n" +
	"\x11ClearLorasRequest\">\n" +
	"\x12ClearLorasResponse\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\"\x12\n" +
	"\x10ListLorasRequest\"0\n" +
	"\x11ListLorasResponse\x12\x1b\n" +
	"\tlora_path\x18\x01 \x03(\tR\bloraPath\"5\n" +
	"\aSetLora\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x02R\x06weight\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\":\n" +
	"\x0eSetLoraRequest\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\";\n" +
	"\x0fSetLoraResponse\x12(\n" +
	"\x05loras\x18\x01 \x03(\v2\x12.generator.SetLoraR\x05loras\"\x85\x01\n" +
	"\x1bGenerateImageToVideoRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12'\n" +
	"\x0fpositive_prompt\x18\x02 \x01(\tR\x0epositivePrompt\x12'\n" +
	"\x0fnegative_prompt\x18\x03 \x01(\tR\x0enegativePrompt\"u\n" +
	"\x1bGenerateImageToVideoResonse\x12\x14\n" +
	"\x05video\x18\x01 \x01(\fR\x05video\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12#\n" +
	"\rfilename_hint\x18\x03 \x01(\tR\ffilenameHint**\n" +
	"\tModelType\x12\v\n" +
	"\a_UNKOWN\x10\x00\x12\a\n" +
	"\x03t2i\x10\x01\x12\a\n" +
	"\x03i2v\x10\x022\xad\x06\n" +
	"\fImageService\x12R\n" +
	"\rGenerateImage\x12\x1f.generator.GenerateImageRequest\x1a .generator.GenerateImageResponse\x12f\n" +
	"\x14GenerateImageToVideo\x12&.generator.GenerateImageToVideoRequest\x1a&.generator.GenerateImageToVideoResonse\x12H\n" +
	"\n" +
	"ListModels\x12\x1c.generator.ListModelsRequest\x1a\x1c.generator.ListModelResponse\x12C\n" +
	"\bSetModel\x12\x1a.generator.SetModelRequest\x1a\x1b.generator.SetModelResponse\x12X\n" +
	"\x0fGetCurrentModel\x12!.generator.GetCurrentModelRequest\x1a\".generator.GetCurrentModelResponse\x12I\n" +
	"\n" +
	"ClearModel\x12\x1c.generator.ClearModelRequest\x1a\x1d.generator.ClearModelResponse\x12F\n" +
	"\tListLoras\x12\x1b.generator.ListLorasRequest\x1a\x1c.generator.ListLorasResponse\x12@\n" +
	"\aSetLora\x12\x19.generator.SetLoraRequest\x1a\x1a.generator.SetLoraResponse\x12X\n" +
	"\x0fGetCurrentLoras\x12!.generator.GetCurrentLorasRequest\x1a\".generator.GetCurrentLorasResponse\x12I\n" +
	"\n" +
	"ClearLoras\x12\x1c.generator.ClearLorasRequest\x1a\x1d.generator.ClearLorasResponseB\bZ\x06proto/b\x06proto3"

var (
	file_image_service_proto_rawDescOnce sync.Once
	file_image_service_proto_rawDescData []byte
)

func file_image_service_proto_rawDescGZIP() []byte {
	file_image_service_proto_rawDescOnce.Do(func() {
		file_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_service_proto_rawDesc), len(file_image_service_proto_rawDesc)))
	})
	return file_image_service_proto_rawDescData
}

var file_image_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_image_service_proto_goTypes = []any{
	(ModelType)(0),                      // 0: generator.ModelType
	(*GenerateImageRequest)(nil),        // 1: generator.GenerateImageRequest
	(*GenerateImageResponse)(nil),       // 2: generator.GenerateImageResponse
	(*ListModelsRequest)(nil),           // 3: generator.ListModelsRequest
	(*ListModelResponse)(nil),           // 4: generator.ListModelResponse
	(*SetModelRequest)(nil),             // 5: generator.SetModelRequest
	(*SetModelResponse)(nil),            // 6: generator.SetModelResponse
	(*GetCurrentModelRequest)(nil),      // 7: generator.GetCurrentModelRequest
	(*GetCurrentModelResponse)(nil),     // 8: generator.GetCurrentModelResponse
	(*ClearModelRequest)(nil),           // 9: generator.ClearModelRequest
	(*ClearModelResponse)(nil),          // 10: generator.ClearModelResponse
	(*GetCurrentLorasRequest)(nil),      // 11: generator.GetCurrentLorasRequest
	(*GetCurrentLorasResponse)(nil),     // 12: generator.GetCurrentLorasResponse
	(*ClearLorasRequest)(nil),           // 13: generator.ClearLorasRequest
	(*ClearLorasResponse)(nil),          // 14: generator.ClearLorasResponse
	(*ListLorasRequest)(nil),            // 15: generator.ListLorasRequest
	(*ListLorasResponse)(nil),           // 16: generator.ListLorasResponse
	(*SetLora)(nil),                     // 17: generator.SetLora
	(*SetLoraRequest)(nil),              // 18: generator.SetLoraRequest
	(*SetLoraResponse)(nil),             // 19: generator.SetLoraResponse
	(*GenerateImageToVideoRequest)(nil), // 20: generator.GenerateImageToVideoRequest
	(*GenerateImageToVideoResonse)(nil), // 21: generator.GenerateImageToVideoResonse
}
var file_image_service_proto_depIdxs = []int32{
	0,  // 0: generator.SetModelRequest.model_type:type_name -> generator.ModelType
	17, // 1: generator.ClearModelResponse.loras:type_name -> generator.SetLora
	17, // 2: generator.GetCurrentLorasResponse.loras:type_name -> generator.SetLora
	17, // 3: generator.ClearLorasResponse.loras:type_name -> generator.SetLora
	17, // 4: generator.SetLoraRequest.loras:type_name -> generator.SetLora
	17, // 5: generator.SetLoraResponse.loras:type_name -> generator.SetLora
	1,  // 6: generator.ImageService.GenerateImage:input_type -> generator.GenerateImageRequest
	20, // 7: generator.ImageService.GenerateImageToVideo:input_type -> generator.GenerateImageToVideoRequest
	3,  // 8: generator.ImageService.ListModels:input_type -> generator.ListModelsRequest
	5,  // 9: generator.ImageService.SetModel:input_type -> generator.SetModelRequest
	7,  // 10: generator.ImageService.GetCurrentModel:input_type -> generator.GetCurrentModelRequest
	9,  // 11: generator.ImageService.ClearModel:input_type -> generator.ClearModelRequest
	15, // 12: generator.ImageService.ListLoras:input_type -> generator.ListLorasRequest
	18, // 13: generator.ImageService.SetLora:input_type -> generator.SetLoraRequest
	11, // 14: generator.ImageService.GetCurrentLoras:input_type -> generator.GetCurrentLorasRequest
	13, // 15: generator.ImageService.ClearLoras:input_type -> generator.ClearLorasRequest
	2,  // 16: generator.ImageService.GenerateImage:output_type -> generator.GenerateImageResponse
	21, // 17: generator.ImageService.GenerateImageToVideo:output_type -> generator.GenerateImageToVideoResonse
	4,  // 18: generator.ImageService.ListModels:output_type -> generator.ListModelResponse
	6,  // 19: generator.ImageService.SetModel:output_type -> generator.SetModelResponse
	8,  // 20: generator.ImageService.GetCurrentModel:output_type -> generator.GetCurrentModelResponse
	10, // 21: generator.ImageService.ClearModel:output_type -> generator.ClearModelResponse
	16, // 22: generator.ImageService.ListLoras:output_type -> generator.ListLorasResponse
	19, // 23: generator.ImageService.SetLora:output_type -> generator.SetLoraResponse
	12, // 24: generator.ImageService.GetCurrentLoras:output_type -> generator.GetCurrentLorasResponse
	14, // 25: generator.ImageService.ClearLoras:output_type -> generator.ClearLorasResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_image_service_proto_init() }
func file_image_service_proto_init() {
	if File_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_service_proto_rawDesc), len(file_image_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_service_proto_goTypes,
		DependencyIndexes: file_image_service_proto_depIdxs,
		EnumInfos:         file_image_service_proto_enumTypes,
		MessageInfos:      file_image_service_proto_msgTypes,
	}.Build()
	File_image_service_proto = out.File
	file_image_service_proto_goTypes = nil
	file_image_service_proto_depIdxs = nil
}
