// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: image_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PositivePrompt string                 `protobuf:"bytes,1,opt,name=positive_prompt,json=positivePrompt,proto3" json:"positive_prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,2,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetPositivePrompt() string {
	if x != nil {
		return x.PositivePrompt
	}
	return ""
}

func (x *GenerateImageRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilenameHint  string                 `protobuf:"bytes,3,opt,name=filename_hint,json=filenameHint,proto3" json:"filename_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateImageResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateImageResponse) GetFilenameHint() string {
	if x != nil {
		return x.FilenameHint
	}
	return ""
}

type GenerateImageToVideoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Image          []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	PositivePrompt string                 `protobuf:"bytes,1,opt,name=positive_prompt,json=positivePrompt,proto3" json:"positive_prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,2,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImageToVideoRequest) Reset() {
	*x = GenerateImageToVideoRequest{}
	mi := &file_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageToVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageToVideoRequest) ProtoMessage() {}

func (x *GenerateImageToVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageToVideoRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageToVideoRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateImageToVideoRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateImageToVideoRequest) GetPositivePrompt() string {
	if x != nil {
		return x.PositivePrompt
	}
	return ""
}

func (x *GenerateImageToVideoRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

type GenerateImageToVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         []byte                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilenameHint  string                 `protobuf:"bytes,3,opt,name=filename_hint,json=filenameHint,proto3" json:"filename_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageToVideoResponse) Reset() {
	*x = GenerateImageToVideoResponse{}
	mi := &file_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageToVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageToVideoResponse) ProtoMessage() {}

func (x *GenerateImageToVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageToVideoResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageToVideoResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateImageToVideoResponse) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *GenerateImageToVideoResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateImageToVideoResponse) GetFilenameHint() string {
	if x != nil {
		return x.FilenameHint
	}
	return ""
}

var File_image_service_proto protoreflect.FileDescriptor

const file_image_service_proto_rawDesc = "" +
	"\n" +
	"\x13image_service.proto\x12\tgenerator\"h\n" +
	"\x14GenerateImageRequest\x12'\n" +
	"\x0fpositive_prompt\x18\x01 \x01(\tR\x0epositivePrompt\x12'\n" +
	"\x0fnegative_prompt\x18\x02 \x01(\tR\x0enegativePrompt\"o\n" +
	"\x15GenerateImageResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12#\n" +
	"\rfilename_hint\x18\x03 \x01(\tR\ffilenameHint\"\x85\x01\n" +
	"\x1bGenerateImageToVideoRequest\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12'\n" +
	"\x0fpositive_prompt\x18\x01 \x01(\tR\x0epositivePrompt\x12'\n" +
	"\x0fnegative_prompt\x18\x02 \x01(\tR\x0enegativePrompt\"v\n" +
	"\x1cGenerateImageToVideoResponse\x12\x14\n" +
	"\x05video\x18\x01 \x01(\fR\x05video\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12#\n" +
	"\rfilename_hint\x18\x03 \x01(\tR\ffilenameHint2\xcf\x01\n" +
	"\x10InferenceService\x12R\n" +
	"\rGenerateImage\x12\x1f.generator.GenerateImageRequest\x1a .generator.GenerateImageResponse\x12g\n" +
	"\x14GenerateImageToVideo\x12&.generator.GenerateImageToVideoRequest\x1a'.generator.GenerateImageToVideoResponseB\bZ\x06proto/b\x06proto3"

var (
	file_image_service_proto_rawDescOnce sync.Once
	file_image_service_proto_rawDescData []byte
)

func file_image_service_proto_rawDescGZIP() []byte {
	file_image_service_proto_rawDescOnce.Do(func() {
		file_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_service_proto_rawDesc), len(file_image_service_proto_rawDesc)))
	})
	return file_image_service_proto_rawDescData
}

var file_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_image_service_proto_goTypes = []any{
	(*GenerateImageRequest)(nil),         // 0: generator.GenerateImageRequest
	(*GenerateImageResponse)(nil),        // 1: generator.GenerateImageResponse
	(*GenerateImageToVideoRequest)(nil),  // 2: generator.GenerateImageToVideoRequest
	(*GenerateImageToVideoResponse)(nil), // 3: generator.GenerateImageToVideoResponse
}
var file_image_service_proto_depIdxs = []int32{
	0, // 0: generator.InferenceService.GenerateImage:input_type -> generator.GenerateImageRequest
	2, // 1: generator.InferenceService.GenerateImageToVideo:input_type -> generator.GenerateImageToVideoRequest
	1, // 2: generator.InferenceService.GenerateImage:output_type -> generator.GenerateImageResponse
	3, // 3: generator.InferenceService.GenerateImageToVideo:output_type -> generator.GenerateImageToVideoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_service_proto_init() }
func file_image_service_proto_init() {
	if File_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_service_proto_rawDesc), len(file_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_service_proto_goTypes,
		DependencyIndexes: file_image_service_proto_depIdxs,
		MessageInfos:      file_image_service_proto_msgTypes,
	}.Build()
	File_image_service_proto = out.File
	file_image_service_proto_goTypes = nil
	file_image_service_proto_depIdxs = nil
}
