// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: image_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageService_GenerateImage_FullMethodName   = "/generator.ImageService/GenerateImage"
	ImageService_ListModels_FullMethodName      = "/generator.ImageService/ListModels"
	ImageService_SetModel_FullMethodName        = "/generator.ImageService/SetModel"
	ImageService_GetCurrentModel_FullMethodName = "/generator.ImageService/GetCurrentModel"
	ImageService_ClearModel_FullMethodName      = "/generator.ImageService/ClearModel"
	ImageService_ListLoras_FullMethodName       = "/generator.ImageService/ListLoras"
	ImageService_SetLora_FullMethodName         = "/generator.ImageService/SetLora"
	ImageService_GetCurrentLoras_FullMethodName = "/generator.ImageService/GetCurrentLoras"
	ImageService_ClearLoras_FullMethodName      = "/generator.ImageService/ClearLoras"
)

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	GenerateImage(ctx context.Context, in *GenerateImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelResponse, error)
	SetModel(ctx context.Context, in *SetModelRequest, opts ...grpc.CallOption) (*SetModelResponse, error)
	GetCurrentModel(ctx context.Context, in *GetCurrentModelRequest, opts ...grpc.CallOption) (*GetCurrentModelResponse, error)
	ClearModel(ctx context.Context, in *ClearModelRequest, opts ...grpc.CallOption) (*ClearModelResponse, error)
	ListLoras(ctx context.Context, in *ListLorasRequest, opts ...grpc.CallOption) (*ListLorasResponse, error)
	SetLora(ctx context.Context, in *SetLoraRequest, opts ...grpc.CallOption) (*SetLoraResponse, error)
	GetCurrentLoras(ctx context.Context, in *GetCurrentLorasRequest, opts ...grpc.CallOption) (*GetCurrentLorasResponse, error)
	ClearLoras(ctx context.Context, in *ClearLorasRequest, opts ...grpc.CallOption) (*ClearLorasResponse, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) GenerateImage(ctx context.Context, in *GenerateImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, ImageService_GenerateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelResponse)
	err := c.cc.Invoke(ctx, ImageService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) SetModel(ctx context.Context, in *SetModelRequest, opts ...grpc.CallOption) (*SetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetModelResponse)
	err := c.cc.Invoke(ctx, ImageService_SetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) GetCurrentModel(ctx context.Context, in *GetCurrentModelRequest, opts ...grpc.CallOption) (*GetCurrentModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentModelResponse)
	err := c.cc.Invoke(ctx, ImageService_GetCurrentModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ClearModel(ctx context.Context, in *ClearModelRequest, opts ...grpc.CallOption) (*ClearModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearModelResponse)
	err := c.cc.Invoke(ctx, ImageService_ClearModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ListLoras(ctx context.Context, in *ListLorasRequest, opts ...grpc.CallOption) (*ListLorasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLorasResponse)
	err := c.cc.Invoke(ctx, ImageService_ListLoras_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) SetLora(ctx context.Context, in *SetLoraRequest, opts ...grpc.CallOption) (*SetLoraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoraResponse)
	err := c.cc.Invoke(ctx, ImageService_SetLora_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) GetCurrentLoras(ctx context.Context, in *GetCurrentLorasRequest, opts ...grpc.CallOption) (*GetCurrentLorasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentLorasResponse)
	err := c.cc.Invoke(ctx, ImageService_GetCurrentLoras_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ClearLoras(ctx context.Context, in *ClearLorasRequest, opts ...grpc.CallOption) (*ClearLorasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearLorasResponse)
	err := c.cc.Invoke(ctx, ImageService_ClearLoras_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility.
type ImageServiceServer interface {
	GenerateImage(context.Context, *GenerateImageRequest) (*GenerateImageResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelResponse, error)
	SetModel(context.Context, *SetModelRequest) (*SetModelResponse, error)
	GetCurrentModel(context.Context, *GetCurrentModelRequest) (*GetCurrentModelResponse, error)
	ClearModel(context.Context, *ClearModelRequest) (*ClearModelResponse, error)
	ListLoras(context.Context, *ListLorasRequest) (*ListLorasResponse, error)
	SetLora(context.Context, *SetLoraRequest) (*SetLoraResponse, error)
	GetCurrentLoras(context.Context, *GetCurrentLorasRequest) (*GetCurrentLorasResponse, error)
	ClearLoras(context.Context, *ClearLorasRequest) (*ClearLorasResponse, error)
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageServiceServer struct{}

func (UnimplementedImageServiceServer) GenerateImage(context.Context, *GenerateImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateImage not implemented")
}
func (UnimplementedImageServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedImageServiceServer) SetModel(context.Context, *SetModelRequest) (*SetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetModel not implemented")
}
func (UnimplementedImageServiceServer) GetCurrentModel(context.Context, *GetCurrentModelRequest) (*GetCurrentModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentModel not implemented")
}
func (UnimplementedImageServiceServer) ClearModel(context.Context, *ClearModelRequest) (*ClearModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearModel not implemented")
}
func (UnimplementedImageServiceServer) ListLoras(context.Context, *ListLorasRequest) (*ListLorasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoras not implemented")
}
func (UnimplementedImageServiceServer) SetLora(context.Context, *SetLoraRequest) (*SetLoraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLora not implemented")
}
func (UnimplementedImageServiceServer) GetCurrentLoras(context.Context, *GetCurrentLorasRequest) (*GetCurrentLorasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentLoras not implemented")
}
func (UnimplementedImageServiceServer) ClearLoras(context.Context, *ClearLorasRequest) (*ClearLorasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearLoras not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}
func (UnimplementedImageServiceServer) testEmbeddedByValue()                      {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	// If the following call panics, it indicates UnimplementedImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_GenerateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GenerateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_GenerateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GenerateImage(ctx, req.(*GenerateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_SetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).SetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_SetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).SetModel(ctx, req.(*SetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_GetCurrentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GetCurrentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_GetCurrentModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GetCurrentModel(ctx, req.(*GetCurrentModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ClearModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ClearModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_ClearModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ClearModel(ctx, req.(*ClearModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ListLoras_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLorasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ListLoras(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_ListLoras_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ListLoras(ctx, req.(*ListLorasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_SetLora_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).SetLora(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_SetLora_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).SetLora(ctx, req.(*SetLoraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_GetCurrentLoras_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentLorasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GetCurrentLoras(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_GetCurrentLoras_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GetCurrentLoras(ctx, req.(*GetCurrentLorasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ClearLoras_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearLorasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ClearLoras(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_ClearLoras_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ClearLoras(ctx, req.(*ClearLorasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "generator.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateImage",
			Handler:    _ImageService_GenerateImage_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ImageService_ListModels_Handler,
		},
		{
			MethodName: "SetModel",
			Handler:    _ImageService_SetModel_Handler,
		},
		{
			MethodName: "GetCurrentModel",
			Handler:    _ImageService_GetCurrentModel_Handler,
		},
		{
			MethodName: "ClearModel",
			Handler:    _ImageService_ClearModel_Handler,
		},
		{
			MethodName: "ListLoras",
			Handler:    _ImageService_ListLoras_Handler,
		},
		{
			MethodName: "SetLora",
			Handler:    _ImageService_SetLora_Handler,
		},
		{
			MethodName: "GetCurrentLoras",
			Handler:    _ImageService_GetCurrentLoras_Handler,
		},
		{
			MethodName: "ClearLoras",
			Handler:    _ImageService_ClearLoras_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image_service.proto",
}
