"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenerateImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITIVE_PROMPT_FIELD_NUMBER: builtins.int
    NEGATIVE_PROMPT_FIELD_NUMBER: builtins.int
    positive_prompt: builtins.str
    negative_prompt: builtins.str
    def __init__(
        self,
        *,
        positive_prompt: builtins.str = ...,
        negative_prompt: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["negative_prompt", b"negative_prompt", "positive_prompt", b"positive_prompt"]) -> None: ...

Global___GenerateImageRequest: typing_extensions.TypeAlias = GenerateImageRequest

@typing.final
class GenerateImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FIELD_NUMBER: builtins.int
    MIME_TYPE_FIELD_NUMBER: builtins.int
    FILENAME_HINT_FIELD_NUMBER: builtins.int
    image: builtins.bytes
    mime_type: builtins.str
    filename_hint: builtins.str
    def __init__(
        self,
        *,
        image: builtins.bytes = ...,
        mime_type: builtins.str = ...,
        filename_hint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filename_hint", b"filename_hint", "image", b"image", "mime_type", b"mime_type"]) -> None: ...

Global___GenerateImageResponse: typing_extensions.TypeAlias = GenerateImageResponse
