# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: img_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'img_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11img_service.proto\x12\tgenerator\"H\n\x14GenerateImageRequest\x12\x17\n\x0fpositive_prompt\x18\x01 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x02 \x01(\t\"P\n\x15GenerateImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x15\n\rfilename_hint\x18\x03 \x01(\t2b\n\x0cImageService\x12R\n\rGenerateImage\x12\x1f.generator.GenerateImageRequest\x1a .generator.GenerateImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'img_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEIMAGEREQUEST']._serialized_start=32
  _globals['_GENERATEIMAGEREQUEST']._serialized_end=104
  _globals['_GENERATEIMAGERESPONSE']._serialized_start=106
  _globals['_GENERATEIMAGERESPONSE']._serialized_end=186
  _globals['_IMAGESERVICE']._serialized_start=188
  _globals['_IMAGESERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
