package config

import "fmt"

// Code generated by gonfig gen-go; DO NOT EDIT.

type Config struct {
	Api struct {
		LogLevel string `yaml:"log_level"`
		Port     string `yaml:"port"`
	} `yaml:"api"`
	AppName string `yaml:"app_name"`
	Env     string `yaml:"env"`
	Rpc     struct {
		Peer string `yaml:"peer"`
		Port string `yaml:"port"`
	} `yaml:"rpc"`
}

func (c Config) Validate() error {
	if c.Api.Port == "" {
		return fmt.Errorf("api.port is required")
	}
	if c.Api.LogLevel == "" {
		return fmt.Errorf("api.log_level is required")
	}
	if c.Rpc.Port == "" {
		return fmt.Errorf("rpc.port is required")
	}
	return nil
}
