package config

import "fmt"

// Code generated by gonfig gen-go; DO NOT EDIT.

type Config struct {
	Api struct {
		AllowedOrigins string `yaml:"allowed_origins"`
		LogLevel       string `yaml:"log_level"`
		Port           string `yaml:"port"`
	} `yaml:"api"`
	AppName string `yaml:"app_name"`
	Env     string `yaml:"env"`
	Rpc     struct {
		DialTimeout  string `yaml:"dial_timeout"`
		I2VTimeout   string `yaml:"i2v_timeout"`
		MaxMsgSizeMB int    `yaml:"max_msg_size_mb"`
		Peer         string `yaml:"peer"`
		Port         string `yaml:"port"`
		T2ITimeout   string `yaml:"t2i_timeout"`
	} `yaml:"rpc"`
}

func (c Config) Validate() error {
	if c.Api.Port == "" {
		return fmt.Errorf("api.port is required")
	}
	if c.Api.LogLevel == "" {
		return fmt.Errorf("api.log_level is required")
	}
	if c.Api.AllowedOrigins == "" {
		return fmt.Errorf("api.allowed_origins is required")
	}
	if c.Rpc.Port == "" {
		return fmt.Errorf("rpc.port is required")
	}
	if c.Rpc.Peer == "" {
		return fmt.Errorf("rpc.peer is required")
	}
	if c.Rpc.DialTimeout == "" {
		return fmt.Errorf("rpc.dial_timeout is required")
	}
	if c.Rpc.T2ITimeout == "" {
		return fmt.Errorf("rpc.t2i_timeout is required")
	}
	if c.Rpc.I2VTimeout == "" {
		return fmt.Errorf("rpc.i2v_timeout is required")
	}
	if c.Rpc.MaxMsgSizeMB <= 0 {
		return fmt.Errorf("rpc.max_msg_size_mb must be > 0")
	}
	return nil
}
