// Code generated by gonfig gen-go; DO NOT EDIT.

package config

import "fmt"

type ApiConfig struct {
	AllowedOrigins string      `yaml:"allowed_origins"`
	Dl             ApiDlConfig `yaml:"dl"`
	LogLevel       string      `yaml:"log_level"`
	Port           string      `yaml:"port"`
}

type ApiDlClientConfig struct {
	ApiKey      string `yaml:"apiKey"`
	DownloadUrl string `yaml:"downloadUrl"`
	ModeInfoUrl string `yaml:"modeInfoUrl"`
}

type ApiDlConfig struct {
	BaseDir       string            `yaml:"baseDir"`
	Client        ApiDlClientConfig `yaml:"client"`
	MaxConcurrent int               `yaml:"maxConcurrent"`
	QueueSize     int               `yaml:"queueSize"`
}

type RpcConfig struct {
	Peer string `yaml:"peer"`
	Port string `yaml:"port"`
}

type Config struct {
	Api     ApiConfig `yaml:"api"`
	AppName string    `yaml:"app_name"`
	Env     string    `yaml:"env"`
	Rpc     RpcConfig `yaml:"rpc"`
}

func (c Config) Validate() error {
	if c.Api.Port == "" {
		return fmt.Errorf("api.port is required")
	}
	if c.Api.LogLevel == "" {
		return fmt.Errorf("api.log_level is required")
	}
	if c.Api.Dl.BaseDir == "" {
		return fmt.Errorf("api.dl.baseDir is required")
	}
	if c.Api.Dl.QueueSize == 0 {
		return fmt.Errorf("api.dl.queueSize is required")
	}
	if c.Api.Dl.QueueSize < 1 {
		return fmt.Errorf("api.dl.queueSize must be >= 1")
	}
	if c.Api.Dl.QueueSize > 10 {
		return fmt.Errorf("api.dl.queueSize must be <= 10")
	}
	if c.Api.Dl.MaxConcurrent == 0 {
		return fmt.Errorf("api.dl.maxConcurrent is required")
	}
	if c.Api.Dl.MaxConcurrent < 1 {
		return fmt.Errorf("api.dl.maxConcurrent must be >= 1")
	}
	if c.Api.Dl.MaxConcurrent > 10 {
		return fmt.Errorf("api.dl.maxConcurrent must be <= 10")
	}
	if c.Api.Dl.Client.DownloadUrl == "" {
		return fmt.Errorf("api.dl.client.downloadUrl is required")
	}
	if c.Api.Dl.Client.ModeInfoUrl == "" {
		return fmt.Errorf("api.dl.client.modeInfoUrl is required")
	}
	if c.Api.Dl.Client.ApiKey == "" {
		return fmt.Errorf("api.dl.client.apiKey is required")
	}
	if c.Rpc.Port == "" {
		return fmt.Errorf("rpc.port is required")
	}
	return nil
}
